# This will run on Travis' 'new' container-based infrastructure
sudo: required

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: elve
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/stdgregwar/elve.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz
before_script:
 - sudo apt-get install build-essential g++ libboost-all-dev libstdc++6 qt5-default qtcreator libqt5svg5-dev

# Build your code e.g. by calling make
script:
  - mkdir build
  - cd build
  - qmake ../elve.pro
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
