# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: cpp
compiler:
 - gcc
# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: elve
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/stdgregwar/elve.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - gpref
      - g++-multilib
      - libc6-dev-i386

# Build your code e.g. by calling make
script:
 - echo "Build? Which build?"
 - git clone https://github.com/mxe/mxe
 - cd mxe
 - make -j8 MXE_TARGETS=i686-w64-mingw32.shared.posix qtbase qtsvg boost
 - export PATH=$HOME/mxe/usr/bin:$PATH
 - cd $TRAVIS_BUILD_DIR
 - $HOME/mxe/usr/i686-w64-mingw32.shared.posix/qt5/bin/qmake $HOME
 - make
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
