# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: elve
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/stdgregwar/elve.git

# Install dependencies
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - qt5-default
      - libqt5svg5-dev

# Build your code e.g. by calling make
script:
  - mkdir build
  - cd build
  - qmake ../elve.pro
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
